// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/connections": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/profile" | "/connections";
  };
  "./layout/base-layout.tsx": {
    id: "layout/base-layout";
    page: "/" | "/profile" | "/connections";
  };
  "../pages/home/ui/page.tsx": {
    id: "../pages/home/ui/page";
    page: "/";
  };
  "../pages/profile/ui/page.tsx": {
    id: "../pages/profile/ui/page";
    page: "/profile";
  };
  "../pages/connections/ui/page.tsx": {
    id: "../pages/connections/ui/page";
    page: "/connections";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layout/base-layout": typeof import("./src/app/./layout/base-layout.tsx");
  "../pages/home/ui/page": unknown;
  "../pages/profile/ui/page": unknown;
  "../pages/connections/ui/page": unknown;
};