// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/connections": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/connections/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/documentations": {
    params: {};
  };
  "/agreements": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/connections" | "/users" | "/connections/:id" | "/profile" | "/documentations" | "/agreements" | "/login" | "/*";
  };
  "./layout/base-layout.tsx": {
    id: "layout/base-layout";
    page: "/" | "/connections" | "/users" | "/connections/:id" | "/profile" | "/documentations" | "/agreements";
  };
  "../pages/home/ui/page.tsx": {
    id: "../pages/home/ui/page";
    page: "/";
  };
  "../pages/connections/ui/page.tsx": {
    id: "../pages/connections/ui/page";
    page: "/connections";
  };
  "../pages/users/ui/page.tsx": {
    id: "../pages/users/ui/page";
    page: "/users";
  };
  "../pages/connections/ui/detail-page.tsx": {
    id: "../pages/connections/ui/detail-page";
    page: "/connections/:id";
  };
  "../pages/profile/ui/page.tsx": {
    id: "../pages/profile/ui/page";
    page: "/profile";
  };
  "../pages/documentations/ui/page.tsx": {
    id: "../pages/documentations/ui/page";
    page: "/documentations";
  };
  "../pages/agreements/ui/page.tsx": {
    id: "../pages/agreements/ui/page";
    page: "/agreements";
  };
  "../pages/auth/ui/login-page.tsx": {
    id: "../pages/auth/ui/login-page";
    page: "/login";
  };
  "./routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layout/base-layout": typeof import("./src/app/./layout/base-layout.tsx");
  "../pages/home/ui/page": unknown;
  "../pages/connections/ui/page": unknown;
  "../pages/users/ui/page": unknown;
  "../pages/connections/ui/detail-page": unknown;
  "../pages/profile/ui/page": unknown;
  "../pages/documentations/ui/page": unknown;
  "../pages/agreements/ui/page": unknown;
  "../pages/auth/ui/login-page": unknown;
  "routes/not-found": typeof import("./src/app/./routes/not-found.tsx");
};